apiVersion: v1
kind: ReplicationController 
metadata:
  name: myonlineapp-rc
spec:
  replicas: 2
  selector:
    app: myonlineapp
    version: 2.6.1
  template: 
    metadata:
     labels:
        app: myonlineapp
        version: 2.6.1
    spec:
        containers:
        - name: myonlineapp-container
          image: umagurram/javaproject28feb:1
          ports:
          - containerPort: 8080
          