apiVersion: v1
kind: ReplicationController 
metadata:
  name: myonlineapp-rc
spec:
  replicas: 3
  selector:
    app: myonlineapp
    version: 2.6.2
  template: 
    metadata:
    labels:
        app: myonlineapp
        version: 2.6.2
    spec:
        containers:
        - name: myonlineapp-container
          image: umagurram/javaproject28feb
          ports:
          - containerPort: 8080